### ISSUE TITLE
Using SOEM 1.3.1. from @OpenEthercatSociety

### ISSUE THREAD

**Issue by MatthijsBurgh** [smits/soem#9]
According to Arthur Ketels, there are some important changes.

**Comment by MatthijsBurgh** [comment]
I tried it myself in tue-robotics but it is giving some problems. Not completely clear what the problem is.

**Comment by k-okada** [comment]
we're discussing this issue on -> https://github.com/smits/soem/issues/5#issuecomment-312472571

> I tried it myself in tue-robotics but it is giving some problems. Not completely clear what the problem is.

do you mean using SOEM 1.3.1 gave you some problems? so we'd better to stay in current version?
